# Generated by Django 6.0.3 on 2026-03-17 20:13

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0018_employerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.PositiveIntegerField()),
                ('start_date', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='فرمت تاریخ تولد => YYYY-MM-DD', regex='^\\d{4}-\\d{2}-\\d{2}')])),
                ('end_date', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='فرمت تاریخ تولد => YYYY-MM-DD', regex='^\\d{4}-\\d{2}-\\d{2}')])),
                ('status', models.CharField(choices=[('pendding', 'درحال بررسی'), ('accept', 'قبول شده'), ('rejected', 'رد شده'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده')], default='pendding', max_length=20)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authentication.category')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_projects', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
