# Generated by Django 6.0.3 on 2026-03-17 20:58

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_employerprofile'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendding', 'درانتظار کارفرما'), ('accepted', 'قبول شده'), ('rejected', 'رد شده')], default='pendding', max_length=20)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'employer'], name='projects_pr_status_bd1722_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'category'], name='projects_pr_status_91658c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'model'], name='projects_pr_status_91da39_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'budget'], name='projects_pr_status_038c6f_idx'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['sender'], name='projects_pr_sender__9ba0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['receiver'], name='projects_pr_receive_3d6c56_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['project'], name='projects_pr_project_29501e_idx'),
        ),
    ]
