# Generated by Django 6.0.3 on 2026-03-19 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrequest_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('pendding', 'درانتظار'), ('accepted', 'قبول شده'), ('rejected', 'رد شده')], default='pendding', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequest',
            unique_together={('project', 'receiver', 'sender')},
        ),
    ]
