# Generated by Django 6.0.3 on 2026-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('pendding', 'درانتظار'), ('accepted', 'قبول شده'), ('rejected', 'رد شده'), ('expired', 'این پروژه را مدل دیگری برداشته')], default='pendding', max_length=20),
        ),
    ]
