# Generated by Django 6.0.3 on 2026-03-20 20:04

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('pendding', 'درانتظار'), ('accepted', 'قبول شده'), ('rejected', 'رد شده'), ('expired', 'این پروژه را مدل دیگری برداشت')], default='pendding', max_length=20),
        ),
    ]
