# Generated by Django 6.0.3 on 2026-03-08 20:43

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است!', regex='^09\\d{9}$')])),
                ('code', models.CharField(max_length=6)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است!', regex='^09\\d{9}$')])),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('national_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='کد ملی نامعتبر است', regex='^\\d{10}$')])),
                ('nationality', models.CharField(max_length=150)),
                ('birth_date', django_jalali.db.models.jDateField()),
                ('gender', models.CharField(choices=[('famale', 'زن'), ('male', 'مرد')])),
                ('status', models.CharField(choices=[('accept', 'تایید شده'), ('reject', 'رد شده'), ('pendding', 'درحال بررسی')], default='reject')),
                ('temp', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['first_name'], name='authenticat_first_n_8011a5_idx')],
            },
        ),
    ]
