# Generated by Django 6.0.3 on 2026-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_birth_date_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('accept', 'تایید شده'), ('reject', 'رد شده'), ('pendding', 'درحال بررسی')], default='pendding'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number'], name='authenticat_phone_n_94bef0_idx'),
        ),
    ]
