# Generated by Django 6.0.3 on 2026-03-11 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_birth_date_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='فرمت تاریخ تولد => YYYY-MM-DD', regex='^\\d{4}-\\d{2}-\\d{2}')]),
        ),
    ]
