# Generated by Django 6.0.3 on 2026-03-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_category_usercategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
