# Generated by Django 6.0.3 on 2026-03-14 16:56

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('skin_color', models.CharField(max_length=150)),
                ('eye_color', models.CharField(max_length=150)),
                ('hair_color', models.CharField(max_length=150)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
