# Generated by Django 6.0.3 on 2026-03-14 17:07

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_technicalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalinfo',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='ImagePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_body_url', models.CharField(blank=True, max_length=350, null=True)),
                ('full_shot_url', models.CharField(blank=True, max_length=350, null=True)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
