# Generated by Django 6.0.3 on 2026-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_technicalinfo_options_imageportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_status',
            field=models.CharField(blank=True, choices=[('unemployed', 'غیر کارفرما'), ('employed', 'کارفرما'), ('student', 'دانشجو'), ('other', 'دیگر')], max_length=10, null=True),
        ),
    ]
