# Generated by Django 6.0.3 on 2026-03-14 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='step_reg',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
