# Generated by Django 6.0.3 on 2026-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_step_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
