# Generated by Django 6.0.3 on 2026-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_usercategory_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='imageportfolio',
            name='full_body_url',
            field=models.ImageField(upload_to='portfolio/full-body'),
        ),
        migrations.AlterField(
            model_name='imageportfolio',
            name='full_shot_url',
            field=models.ImageField(upload_to='portfolio/full-shot'),
        ),
    ]
