# Generated by Django 6.0.3 on 2026-03-16 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='step_reg',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
