# Generated by Django 6.0.3 on 2026-03-16 19:08

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_step_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageportfolio',
            name='full_body_url',
            field=models.ImageField(upload_to=apps.authentication.models.portfolio_upload_path),
        ),
        migrations.AlterField(
            model_name='imageportfolio',
            name='full_shot_url',
            field=models.ImageField(upload_to=apps.authentication.models.portfolio_upload_path),
        ),
    ]
