# Generated by Django 6.0.3 on 2026-03-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(blank=True, choices=[('system', 'سیستم'), ('promotion', 'پروموشن'), ('warning', 'خطر'), ('info', 'اطلاعات')], max_length=25, null=True),
        ),
    ]
