# Generated by Django 6.0.3 on 2026-03-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationrecipient',
            old_name='user',
            new_name='receiver',
        ),
    ]
